# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

import re
from typing import Protocol, Sequence


WORLD_INTRO_NAME = "intro"


class _TownLocation(Protocol):
    class_name: str
    name: str
    x: float
    z: float


class _WorldConfigSpec(Protocol):
    name: str
    display_name: str
    cell_size: float

    @property
    def centre(self) -> float: ...


def render_config(
    spec: _WorldConfigSpec,
    *,
    milestone: int,
    town_names: Sequence[_TownLocation] = (),
    animated_building_models: Sequence[str] = (),
) -> str:
    centre = int(spec.centre)
    icon_filename = "icon.paa" if bool(getattr(spec, "surface_pass_enabled", False)) else "g.paa"
    names_block = ""
    if town_names:
        entries: list[str] = []
        for location in town_names:
            entries.append(
                f'''        class {location.class_name}
        {{
            name = "{location.name}";
            position[] = {{{location.x:.3f}, {location.z:.3f}, 25}};
        }};'''
            )
        names_block = "\n        class Names\n        {\n" + "\n\n".join(entries) + "\n        };"

    vehicles_block = ""
    if animated_building_models:
        base_class = f"CWR_{spec.name}_ProceduralDoorHouse"
        land_classes: list[str] = []
        for model_path in sorted(set(animated_building_models)):
            normalized_model = model_path.replace("/", "\\")
            filename = normalized_model.rsplit("\\", 1)[-1]
            stem = filename[:-4] if filename.casefold().endswith(".p3d") else filename
            land_classes.append(
                f'''    class Land_{stem}: {base_class}
    {{
        scope = 1;
        model = "\\{normalized_model}";
    }};'''
            )
        vehicles_block = f'''

class CfgVehicles
{{
    // Keep the procedural door base self-contained. OFP/CWA resolves the
    // concrete Land_<p3dName> class by its simulation token, so depending on
    // an externally declared CfgVehicles/House base makes addon load order a
    // parser dependency and can fail with "Undefined base class 'House'".
    class {base_class}
    {{
        scope = 0;
        simulation = "house";
        animated = 1;
        class Animations
        {{
            class Door1
            {{
                type = "rotation";
                animPeriod = 0.8;
                selection = "door1";
                axis = "door1_axis";
                angle0 = 0;
                angle1 = -1.570796;
            }};
        }};
        class UserActions
        {{
            class OpenDoor1
            {{
                displayName = "Open door";
                position = "door1_action";
                radius = 5.0;
                condition = "this animationPhase ""Door1"" < 0.5";
                statement = "this animate [""Door1"", 1]";
                onlyForPlayer = 1;
            }};
            class CloseDoor1
            {{
                displayName = "Close door";
                position = "door1_action";
                radius = 5.0;
                condition = "this animationPhase ""Door1"" >= 0.5";
                statement = "this animate [""Door1"", 0]";
                onlyForPlayer = 1;
            }};
            class OpenDoor1Inside
            {{
                displayName = "Open door";
                position = "door1_action_inside";
                radius = 5.0;
                condition = "this animationPhase ""Door1"" < 0.5";
                statement = "this animate [""Door1"", 1]";
                onlyForPlayer = 1;
            }};
            class CloseDoor1Inside
            {{
                displayName = "Close door";
                position = "door1_action_inside";
                radius = 5.0;
                condition = "this animationPhase ""Door1"" >= 0.5";
                statement = "this animate [""Door1"", 0]";
                onlyForPlayer = 1;
            }};
        }};
    }};

{chr(10).join(land_classes)}
}};'''

    return f'''// Generated by cwr-worldgen Milestone {milestone}.
// RVW4 and PAA output follows the legacy OFP/CWA serializer conventions.

class CfgPatches
{{
    class {spec.name}
    {{
        units[] = {{}};
        weapons[] = {{}};
        worlds[] = {{"{spec.name}"}};
        requiredVersion = 1.75;
        requiredAddons[] = {{}};
    }};
}};

class CfgWorlds
{{
    // The CWA parser rejects C++-style bare class declarations. This is the
    // traditional OFP island inheritance form used by working community maps.
    class DefaultWorld {{}};
    class Intro: DefaultWorld {{}};

    class {spec.name}: Intro
    {{
        access = 3;
        description = "{spec.display_name}";
        worldName = "\\{spec.name}\\{spec.name}.wrp";
        cutscenes[] = {{"{WORLD_INTRO_NAME}"}};
        icon = "\\{spec.name}\\data\\{icon_filename}";
        longitude = 0;
        latitude = 0;
        landGrid = {spec.cell_size:g};
        centerPosition[] = {{{centre}, {centre}, 0}};
        seagullPos[] = {{{centre}, {centre}, 100}};
        startTime = "12:00";
        startDate = "1/6/85";{names_block}
    }};
}};

class CfgWorldList
{{
    class {spec.name} {{}};
}};{vehicles_block}
'''


def render_mission(
    spec: _WorldConfigSpec,
    *,
    spawn_x: float,
    spawn_z: float,
    milestone: int,
) -> str:
    return f'''version=11;
class Mission
{{
    addOns[]={{"{spec.name}"}};
    addOnsAuto[]={{"{spec.name}"}};
    randomSeed=1234;
    class Intel
    {{
        briefingName="{spec.display_name} Smoke Test";
        briefingDescription="Generated Milestone {milestone} terrain smoke test";
        startWeather=0.200000;
        forecastWeather=0.200000;
        year=1985;
        month=6;
        day=1;
        hour=12;
        minute=0;
    }};
    class Groups
    {{
        items=1;
        class Item0
        {{
            side="WEST";
            class Vehicles
            {{
                items=1;
                class Item0
                {{
                    position[]={{{spawn_x:.3f},0.000,{spawn_z:.3f}}};
                    azimut=0.000000;
                    id=0;
                    side="WEST";
                    vehicle="SoldierWB";
                    player="PLAYER COMMANDER";
                    leader=1;
                    skill=0.600000;
                }};
            }};
        }};
    }};
}};
class Intro
{{
    randomSeed=1;
    class Intel {{}};
}};
class OutroWin
{{
    randomSeed=2;
    class Intel {{}};
}};
class OutroLoose
{{
    randomSeed=3;
    class Intel {{}};
}};
'''


def render_world_intro_mission(
    spec: _WorldConfigSpec,
    *,
    spawn_x: float,
    spawn_z: float,
) -> str:
    """Render the menu intro selected by CfgWorlds/<world>/cutscenes[]."""
    return f'''version=10;
class Mission
{{
    class Intel
    {{
    }};
}};
class Intro
{{
    addOns[]={{"{spec.name}"}};
    addOnsAuto[]={{"{spec.name}"}};
    randomSeed=4321;
    class Intel
    {{
        year=1985;
        month=6;
        day=1;
        hour=12;
        minute=0;
    }};
    class Groups
    {{
        items=1;
        class Item0
        {{
            side="WEST";
            class Vehicles
            {{
                items=1;
                class Item0
                {{
                    position[]={{{spawn_x:.3f},0.000,{spawn_z:.3f}}};
                    id=0;
                    side="WEST";
                    vehicle="SoldierWB";
                    player="PLAYER COMMANDER";
                    leader=1;
                }};
            }};
        }};
    }};
}};
'''


def render_world_intro_script(*, spawn_x: float, spawn_z: float) -> str:
    return f'''_cam = "camera" camCreate [{spawn_x:.3f},20.000,{spawn_z:.3f}]
_cam cameraEffect ["internal","back"]
_cam camSetTarget player
_cam camSetRelPos [0,-8,3]
_cam camCommit 0
@camCommitted _cam
#loop
~1
goto "loop"
'''


_BARE_CLASS_DECLARATION = re.compile(r"\bclass\s+[A-Za-z_][A-Za-z0-9_]*\s*;")


def validate_cwa_config(text: str) -> None:
    """Reject syntax known to be unsupported by the OFP/CWA config parser."""
    bare = _BARE_CLASS_DECLARATION.search(text)
    if bare:
        raise ValueError(f"CWA config contains unsupported bare class declaration: {bare.group(0)}")

    # CWA resolves inheritance while parsing the current config tree. Generated
    # configs therefore must not inherit from an undeclared external class: a
    # reference such as ``class Foo: House`` can abort addon loading before the
    # rest of the file is parsed. Require every base used by our generated text
    # to have appeared earlier in the same file.
    declared_classes: set[str] = set()
    class_with_body = re.compile(
        r"\bclass\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*([A-Za-z_][A-Za-z0-9_]*))?\s*\{"
    )
    for match in class_with_body.finditer(text):
        class_name, base_name = match.groups()
        if base_name and base_name not in declared_classes:
            raise ValueError(
                f"CWA config class {class_name} inherits from undeclared base class {base_name}"
            )
        declared_classes.add(class_name)

    depth = 0
    in_string = False
    escaped = False
    index = 0
    while index < len(text):
        char = text[index]
        next_char = text[index + 1] if index + 1 < len(text) else ""
        if not in_string and char == "/" and next_char == "/":
            newline = text.find("\n", index + 2)
            if newline < 0:
                break
            index = newline + 1
            continue
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
        elif char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth < 0:
                raise ValueError("CWA config has an unmatched closing brace")
        index += 1

    if in_string:
        raise ValueError("CWA config has an unterminated string")
    if depth != 0:
        raise ValueError("CWA config has unbalanced braces")
